#!/usr/bin/env python3
import glob
import os
import sys

def build_docker_image(dockerfile):
    tag = 'packaging/' + dockerfile.split(os.path.sep)[-2]
    os.system('docker build -t {} {}'.format(tag, os.path.dirname(dockerfile)))


def main():
    workdir = os.path.abspath(os.path.dirname(__file__))
    for dockerfile in glob.glob(workdir + '/**/Dockerfile'):
        build_docker_image(dockerfile)


if __name__ == '__main__':
    sys.exit(main())
