# https://fedoraproject.org/wiki/How_to_create_an_RPM_package

FROM ubuntu:16.04

MAINTAINER ChangZhuo Chen (陳昌倬) <czchen@czchen.org>

RUN apt update \
    && apt install -y \
        git \
        snapcraft \
        vim \
    && apt clean
